config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get 'register' => 'users#new' 
  get 'login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'


  resources :posts, except: [:destroy] do 
    member do
      post :vote 
      delete :unvote     
    end
 
    resources :comments, only:[:create,:destroy]  do 
      member do 
        post :vote
        delete :unvote
      end
      
    end
  end

  resources :categories, only: [:show, :new, :create]
    
  resources :users, only:[:create, :edit, :update, :show]

end 

app/models/category.rb
class Category < ActiveRecord::Base
has_many :category_posts
has_many :posts, through: :category_posts

validates :name, presence:true, :uniqueness => true
end

app/models/category_post.rb
class CategoryPost < ActiveRecord::Base
  belongs_to :post 
  belongs_to :category 
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post
    belongs_to :creator, class_name: "User", foreign_key: "user_id"
    has_many :votes, :as => :voteable
    validates :body, presence:true

    include Voteable
end

app/models/concerns/voteable.rb
module Voteable

  def total_votes
    up_votes - down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end

  def down_votes
    self.votes.where(vote: false).size
  end

end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, class_name: "User", foreign_key: "user_id" 
  has_many :comments
  has_many :category_posts
  has_many :categories, through: :category_posts 
  has_many :votes, :as => :voteable

  validates :title, presence:true
  validates :url, presence:true
  validates :description, presence:true

  include Voteable


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :votes
  
  validates :username, presence:true, uniqueness: true
  validates :password, presence:true, length: {minimum: 5}, on: :create

  has_secure_password validations: false




end

app/models/vote.rb
class Vote < ActiveRecord::Base
belongs_to :creator, class_name: "User", foreign_key: "user_id"
belongs_to :voteable, :polymorphic => true
validates_uniqueness_of :creator, scope: [:voteable_type, :voteable_id]
end

app/models/vote_count.rb
module VoteCount

  def total_votes
    up_votes - down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end

  def down_votes
    self.votes.where(vote: false).size
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


helper_method :current_user, :logged_in?, :posts_voted_by_users

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] #Will return nil if session[:user_id] does not exist instead of exception
    # ^^ Memoization: This means User.find will only execute if @current_user doesn't exist  
  end

  def logged_in?
      !!current_user #!! turns obj into boolean.  
  end

  def require_user
    if !logged_in?
      flash[:error]= "Must be logged in to do that"
      redirect_to root_path
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, except:[:show]

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash["notice"]= "Created #{@category.name}"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  
  end

  def update
  
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end


end

app/controllers/category_posts_controller.rb
class CategoryPostsController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
  
  def create
    @post= Post.find(params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.creator= User.find(session[:user_id])
    if @comment.save
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def edit
  end

  def update
  end

  def vote
    comment = Comment.find(params[:id])
    vote = Vote.create(voteable:comment, creator:current_user,vote:params[:vote])
    if vote.valid?
      flash["success"]= 'Your vote was counted'
    else
      flash['alert'] ='You can only vote on a comment once'
    end
    redirect_to :back
  end

  def unvote
    comment = Comment.find(params[:id])
    vote = comment.votes.where(user_id:current_user)
    vote.delete(vote)
    redirect_to :back
  end

  def destroy
    post=Post.find(params[:post_id])
    comment=Comment.find(params[:id])
    comment.delete
    redirect_to :back
  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :set_post, only:[:vote,:show, :edit, :update]
  before_action :require_user, except:[:index,:show]

  def index
    @posts= Post.all  
    flash["alert"]= params[:error]
  end

  def show
    @comment = Comment.new
  end
  
  def vote
    @vote= Vote.create(voteable:@post, creator:current_user,vote:params[:vote])
    respond_to do |format|
      format.html do
        if @vote.valid? 
          flash['success']='Your vote was counted'
        else
          @vote.delete
        end
        redirect_to :back
      end
    format.js 
    end
  end

  def unvote
    post = Post.find(params[:id])
    vote = post.votes.find_by(creator:current_user)
    vote.delete
    redirect_to :back
  end

  def change_vote

  end


  def new
    @post = Post.new
  end

  def create
    @post= Post.new(post_params)
    @post.creator = current_user
    if @post.save
      flash["Success"]= "Saved"
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash["success"]= "Post has been edited"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :url, :creator, :description, :category_ids =>[])
  end
  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by_username(params[:username])

    if user && user.authenticate(params[:password])
        session[:user_id]= user.id #Cookie has a suze limitation so only save id and not User obj.
        flash[:notice]="Your are logged in"
        redirect_to root_path
    else
        flash['error']= "There's something wrong with your username/password"
        render :new
    end
 
  end


  def destroy

    session[:user_id]=nil
    redirect_to root_path

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit,:update]

  def new
    @user =  User.new
  end

  def show 
    @user=User.find(params[:id])
  end



  def create
    @user = User.new(user_params)    
    if @user.save
      session[:user_id]= @user.id 
      flash['success']="Account successfully created"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit 
  end

  def update
    if @user.update(user_params)
      flash['success']="Profile successfully updated"
      redirect_to user_path(@user)
    else 
      render :edit
    end
  end
private

  def set_user 
    @user=User.find(session[:user_id])
  end

  def require_same_user
    if current_user != @user 
      flash['alert']= "You can't do that"
      redirect_to root_path
    end
  end 

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when "notice"then "alert alert-info"
      when "success" then "alert alert-success"
      when "error" then "alert alert-error"
      when "alert" then "alert alert-error"
    end
  end

  def fix_url(url)
    url.starts_with?("http://") ? url: "http://#{url}"
  end

  def display_datetime(post_or_comment)
    post_or_comment.created_at.strftime("%I:%M on %B %d, %Y")
  end

  def render_link_to_posts_path
      link_to posts_path, remote: true
  end

end

app/views/categories/_category.html.erb
<span class='badge'><%=link_to category.name, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'Create A New Category' %>

  <%=render 'shared/errors', obj:@category%>


<div class='well'>

  <%=form_for @category do |f| %>
  <div class='control-group'>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
    <%= f.submit :submit, class: 'btn btn-success' %>
 
  <% end %>

</div>

app/views/categories/show.html.erb
<% header = link_to('All Posts', posts_path) + " &raquo; #{@category.name}".html_safe  %>

<%= render 'shared/content_title', title: header %>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post:post%>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class = "<%= flash_class(name)%>">
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <li>
    <%= link_to 'link', '' %>
  </li>
</ul>
<% if logged_in? %>
<div class= 'nav_item'>
    <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small'  %>
</div>
<% end %>
<div class= 'btn-group nav_item'>
    <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
   Categories <span class='caret'></span></a> 
   <% end %>
      <ul class='dropdown-menu'>
        <% Category.order("lower(name)ASC").all.each do |category| %>
          <li> <%= link_to category.name, category_path(category) %> </li>
        <% end %>
      
      <li class='divider'></li>
      <%if logged_in? %>
        <li>
          <%= link_to(new_category_path) do %>
          <i class='icon-plus'></i>
            New Category
          <% end %>
      <% end %>
        <li>
      </ul>
</div>

<% if logged_in? %>
    <div class= 'btn-group nav_item'>
      <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
        <%= current_user.username %> <span class='caret'></span></a> 
      <% end %>
      <ul class= 'dropdown-menu'>
        <li>
          <%=link_to edit_user_path(current_user) do %>
            <i class='icon-pencil'></i>
            Edit Profile
            <% end %>
        </li>
        <li>
          <%= link_to user_path(current_user) do%>
            <i class='icon-user'></i>
            Profile
          <% end %> 

        </li>
        <li><%= link_to 'Logout', logout_path, method: :delete %></li>

      </ul>
    </div>

<% else %>
  <div class= 'nav_item btn btn-small'>
    <%= link_to 'Register', register_path %>
  </div>

  <div class= 'nav_item btn btn-small'>
    <%= link_to 'Login', login_path %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_comment.html.erb
<% show_post||= false %>

<div class= 'row'>
  <div class='span0 well text-center'>
    <%=  render 'posts/votes', obj:comment,voteable_type:'comment'%>
  </div>
  <div class='container'>
    <div class='well span8'>
      <em>"<%= comment.body%>"</em>
        <% if show_post == true %>
          on <%= link_to(comment.post.title, post_path(comment.post))%>
        <% end%>
        <p>
          <%= render 'shared/creator', name:link_to(comment.creator.username, user_path(comment.creator.id)), time: display_datetime(comment) %>
          <% if comment.creator == current_user %>
            <br><small>
              <%=link_to 'delete',post_comment_path(comment.post,comment),method: 'delete' %>
            </small>
          <% end %>
        </p>  
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post%>

<div class= 'well'>
  <%= form_for @post do |f| %>
    <div class='control-group'>
      <%=  f.label :title  %>
      <%=  f.text_field :title %>
    </div>
    
    <p>
      <div class='control-group'>
        <%= f.label :url %>
        <%=  f.text_field :url %>
      </div>
    </p>
    
    <div class='control-group'>
      <%= f.label :description %>
      <%= f.text_area :description, rows:5%>
    </div>
<br/>

<br>

<p>
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text}%> 
  <% end %>
</p>

<br>
<%= f.submit %>
  <% end %>
  
</div>


<!-- 
 <%= select_tag 'post[category_ids]', options_for_select(Category.all.collect{|category| [category.name, category.id]}), {:multiple=>true}%>
 
 -->

app/views/posts/_post.html.erb
<div class = 'row'>
  <div class='span0 well text-center'>
    <%=  render 'posts/votes', voteable_type:'post',post:post,obj:post%>
  </div>
  <div class= 'container'>
    <div class='span8 well'>
      <%= render post.categories%>
      <h4><%= link_to post.title, fix_url(post.url) %> </h4>
      <p><%= post.description %></p>
      <p><%= render 'shared/creator', name:link_to(post.creator.username, user_path(post.creator)), time: display_datetime(post) %></p>
      <small>
        <span>
          <%= link_to("#{post.comments.size} comments", post_path(post)) %>
        </span>
      </small>
    </div>
  </div>
</div>

app/views/posts/_votes.html.erb
<% if !logged_in?%>
    <%=link_to "Vote", root_path(error:"Must be logged in to vote") %>
 <% elsif voteable_type == 'comment' %>
  <% if obj.votes.where(user_id:current_user).exists?%>
    <%= obj.total_votes %> votes </br>
    <%= link_to "Unvote",unvote_post_comment_path(obj.post,obj), method: 'delete',remote: true %>
  <% else %>
    <span id='up'><%=link_to vote_post_comment_path(obj.post,obj,vote: true), method: 'post', remote: true  do %></span>
      <i class='icon-arrow-up'></i></br>
    <% end %>
    <%= obj.total_votes %> Votes</br>
    <%=link_to vote_post_comment_path(obj.post,obj,vote: false), method: 'post' do %>  
      <i class='icon-arrow-down'></i>
    <% end %>
  <% end %>

<% elsif voteable_type ==  'post' %>


    <%=link_to vote_post_path(post,vote: true), method: 'post',remote: true  do %>
    <span id="true_<%=post.id%>_vote"><i class="icon-arrow-up" ></i></span></br>
    <% end %>
       <span id='post_<%=post.id%>_votes'><%= obj.total_votes %></span>  Votes</br>
    <%=link_to vote_post_path(post,vote: false), method: 'post', remote: true do %>  
    <span id="false_<%=post.id%>_vote"><i class='icon-arrow-down'></i></span>
    <% end %>
  <% end %>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: "Edit your Post"%>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "Posts"%>
<% @posts.each do |post| %>
  <%= render 'post', post:post, remote: true %>
<% end %>

app/views/posts/index.js.erb
$("#true_<%=post.id%>_vote").css("opacity", "0.5")

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a New Post' %>

<%= render 'form' %>

app/views/posts/show.html.erb
<% if @post.creator == current_user %>
  <p class='pull-right'> 
    [<%= link_to 'edit this post', edit_post_path(@post) %>]
  <p>
<% end %>

<%= render @post.categories%></p>

<p>
  <%= render 'shared/content_title', title: @post.title%>
</p>


  <%= render 'post', post: @post %>
<hr width='85%'>
<h4>Comments</h4>
<%= render 'shared/errors', obj:@comment %>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <div class='control-group'>
      <%= f.text_area :body, rows:5, class:'span10'%>  
    </div>
      <%= f.submit 'submit'%>
  <% end %>
<% end %>

<% @post.comments.each do |comment| %>

<%= render 'comment', comment: comment%>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
    $("#<%=params[:vote]%>_<%=@post.id%>_vote").css("opacity", "0.5")
<% else %>
  <% vote= Vote.where(user_id:current_user, voteable_id:@vote.voteable_id,voteable_type:@vote.voteable_type) %>
  <% vote.delete(vote) %>
  $("#<%=params[:vote]%>_<%=@post.id%>_vote").css("opacity", "1")
<% end %>

$('#post_<%=@post.id%>_votes').html('<%=@post.total_votes%>')

app/views/shared/_content_title.html.erb
<p class = 'lead'>
  <%= title %>
  <hr width='85%'>
</p>

app/views/shared/_creator.html.erb
<span class= 'quiet'> 
  <small>posted by <%=name%> at <%=time%> </small>
</span>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>  
  <div class = 'row'>
    <div class='alert alert-error span8'>
      <h5>The following errors needs attention:</h5>
      <% obj.errors.full_messages. each do |msg| %>
        <ul>  
          <li><%= msg %></li> 
        </ul>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render '/shared/errors', obj: @user %>
<div class='well span6'>
<%= form_for @user do |f| %>
<div class ='group-control'>
<%= f.label :username %>
<%= f.text_field :username%>
</div>

<div class='group-control'>
<%=f.label :password%>
<%=f.password_field :password%>
</div>

<%= f.submit (f.object.new_record? ? "Register" : "Update"), class: 'btn btn-success' %>
<% end %>

</div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Profile'%>
<%=render 'form'%>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'Register'%>
<%= render 'form'%>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "Profile: #{@user.username}" %>

<div class = 'well'>
  <dl class= 'dl-horizontal'>
    <dt>Username:</dt>
    <dd><%= @user.username %></dd>
  </dl>
</div>

<h4><%= @user.username %>'s Activity </h4>
  <div class="container-fluid">
    <ul class='nav nav-tabs'>
      <li class=<%= 'active' if params[:tab].nil? %> >
        <%= link_to "Posts (#{@user.posts.size})", user_path(@user) %>
      </li>
      <li class='<%='active' if params[:tab]== 'comments'%>'>
        <%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: 'comments') %>
      </li> 
    </ul>

    <% if params[:tab].nil? %>
      <% @user.posts.each do |post|%>
        <%= render 'posts/post', post:post %>            
      <% end %>
    <% elsif params[:tab]=='comments' %>
      <% @user.comments.each do |comment| %>
        <%= render 'posts/comment', comment: comment, show_post: true %>
      <% end %>
    <% end %>

      </div>
    </div>
  </div>
</div>